### ISSUE TITLE
dutch language update

### ISSUE THREAD

**Issue by Faynominaal82** [PickleModifications/pickle_slapboxing#7]
Language["nl"] = {
    table_already_placed = "Je hebt al een tafel geplaatst, verwijder deze voordat je een andere plaatst.",
    table_interact_home = "Druk ~INPUT_CONTEXT~ voor het thuisteam.",
    table_interact_away = "Druk ~INPUT_CONTEXT~ voor het uitteam.",
    table_interact_menu = "Druk ~INPUT_CONTEXT~ voor interactie aan de wedstrijd.",
    table_interact_start = "Druk ~INPUT_CONTEXT~ om deze wedstrijd te starten.\nDruk ~INPUT_CELLPHONE_CANCEL~ om de tafel te verlaten.",
    table_match_wait = "Wachten tot je tegenstander zich aansluit.\nPress ~INPUT_CELLPHONE_CANCEL~ om de tafel te verlaten.",
    table_match_occupied = "Het %s team is al bezet.",
    table_match_joined = "You have joined the %s team.",
    table_match_left = "Je bent lid geworden van het %s team.",
    table_match_slap = "Begin op de ~INPUT_CONTEXT~ spier te slaan om ze te het licht uit de ogen te slaan.",
    table_match_spam = "Blijf slaan op de ~INPUT_CONTEXT~ spier voor meer kracht.",
    table_match_waitslap = "Wees klaar om geslagen te worden.",
    match_win = "Je hebt $%s van de wedstrijd gewonnen!",
    match_lose = "Je hebt $%s van de wedstrijd verloren.",
    match_refund = "Je hebt $%s teruggekregen van de wedstrijd.",
    bet_menu_title = "Wedden (%s team).",
    bet_menu_one = "Inzet bedrag",
    bet_already = "Je hebt al een weddenschap voor deze wedstrijd.",
    bet_not_afford = "Je kunt het je niet veroorloven om zoveel in te zetten.",
    bet_placed = "Je hebt $%s in het %s team geplaatst.",
    bet_active = "Je kunt niet wedden op een actieve wedstrijd.",
    table_menu_title = "Strijders",
    table_fighter = "Strijder ID: %s.",
    table_fighter_title = "Strijder #%s - %s (Huidige inzet: $%s)",
    table_fighter_none = "Geen vechter in dit team.",
    table_spawned = "Je hebt een tafel geplaatst.",
    table_removed = "Je hebt een tafel opgepakt.",
    table_remove = "Pak tafel op",
    table_remove_desc = "Verwijdert de tafel.",
    table_fail_removed = "U kunt deze tafel niet oppakken.",
    home = "Thuis",
    away = "Uit"
}

**Comment by PickleModifications** [comment]
Please submit a PR for this.
